pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Build App 1 Docker Image
                script {
                    docker.build("dewan11415/app1:latest", ".")
                }
            }
        }
        stage('Push to DockerHub') {
            steps {
                // Push App 1 Docker Image to DockerHub
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dewan11415-dockerhub') {
                        docker.image("dewan11415/app1:latest").push()
                    }
                }
            }
        }
    }
}

