pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    echo "Building Docker Image..."
                    docker.build("dewan11415/app1:latest", ".")
                }
            }
        }
        stage('Push to DockerHub') {
            steps {
                script {
                    echo "Pushing Docker Image to DockerHub..."
                    docker.withRegistry('registry.hub.docker.com', 'dewan11415-dockerhub') {
                        docker.image("dewan11415/app1:latest").push()
                    }
                }
            }
        }
    }
}


